name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    
    - name: Install CF CLI
      run: curl -L "https://packages.cloudfoundry.org/stable?release=linux64-binary&source=github" | tar -zx

    - name: Log in to PWS
      run: cf login -a api.run.pivotal.io -u ${{ secrets.CF_USERNAME }} -p ${{ secrets.CF_PASSWORD }} -o "Black Girls Code" -s seattle
      
    - name: Deploy app
      run: cf push
